// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"customer/internal/biz"
	"customer/internal/conf"
	"customer/internal/data"
	"customer/internal/server"
	"customer/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	customerRepo := data.NewCustomerRepo(dataData, logger)
	customerUsercase := biz.NewCustomerUsercase(customerRepo, logger)
	customerService := service.NewCustomerService(customerUsercase, logger)
	httpServer := server.NewHTTPServer(confServer, customerService, logger)
	grpcServer := server.NewGRPCServer(confServer, customerService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
